
cd /home/pt40963/scratch/pea_aphid_RNAseq_20171104

# --prep_reference (removed) already done
wait
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep2_R1.fastq.gz --right N116-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep3_R1.fastq.gz --right N116-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep4_R1.fastq.gz --right N116-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left N116-rep5_R1.fastq.gz --right N116-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left PSO1-rep1_R1.fastq.gz --right PSO1-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left PSO1-rep2_R1.fastq.gz --right PSO1-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left PSO1-rep3_R1.fastq.gz --right PSO1-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left PSO1-rep4_R1.fastq.gz --right PSO1-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left PSO1-rep5_R1.fastq.gz --right PSO1-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left avr-rep1_R1.fastq.gz --right avr-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left avr-rep2_R1.fastq.gz --right avr-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left avr-rep3_R1.fastq.gz --right avr-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left avr-rep4_R1.fastq.gz --right avr-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left avr-rep5_R1.fastq.gz --right avr-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left vir-rep1_R1.fastq.gz --right vir-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left vir-rep2_R1.fastq.gz --right vir-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left vir-rep3_R1.fastq.gz --right vir-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left vir-rep4_R1.fastq.gz --right vir-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts good.good.trinity_all_denovo.Trinity.fasta --seqType fq --left vir-rep5_R1.fastq.gz --right vir-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep5

 
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --cross_sample_norm TMM --name_sample_by_basedir ./N116-rep1/abundance.tsv ./N116-rep2/abundance.tsv ./N116-rep3/abundance.tsv ./N116-rep4/abundance.tsv ./N116-rep5/abundance.tsv ./PSO1-rep1/abundance.tsv ./PSO1-rep2/abundance.tsv ./PSO1-rep3/abundance.tsv ./PSO1-rep4/abundance.tsv ./PSO1-rep5/abundance.tsv ./avr-rep1/abundance.tsv ./avr-rep2/abundance.tsv ./avr-rep3/abundance.tsv ./avr-rep4/abundance.tsv ./avr-rep5/abundance.tsv ./vir-rep1/abundance.tsv ./vir-rep2/abundance.tsv ./vir-rep3/abundance.tsv ./vir-rep4/abundance.tsv ./vir-rep5/abundance.tsv --out_prefix N116_PS01_VIRS_AVR_RNAseq_denovo



cd /home/pt40963/scratch/pea_aphid_RNAseq_20171104

# --prep_reference (removed) already done

wait
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep2_R1.fastq.gz --right N116-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep3_R1.fastq.gz --right N116-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep4_R1.fastq.gz --right N116-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left N116-rep5_R1.fastq.gz --right N116-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left PSO1-rep1_R1.fastq.gz --right PSO1-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left PSO1-rep2_R1.fastq.gz --right PSO1-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left PSO1-rep3_R1.fastq.gz --right PSO1-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left PSO1-rep4_R1.fastq.gz --right PSO1-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left PSO1-rep5_R1.fastq.gz --right PSO1-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left avr-rep1_R1.fastq.gz --right avr-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left avr-rep2_R1.fastq.gz --right avr-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left avr-rep3_R1.fastq.gz --right avr-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left avr-rep4_R1.fastq.gz --right avr-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left avr-rep5_R1.fastq.gz --right avr-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left vir-rep1_R1.fastq.gz --right vir-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left vir-rep2_R1.fastq.gz --right vir-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left vir-rep3_R1.fastq.gz --right vir-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left vir-rep4_R1.fastq.gz --right vir-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/pea_aphid_genes_hopefully.fasta --seqType fq --left vir-rep5_R1.fastq.gz --right vir-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep5

 
 /home/pt40963/Downloads/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --cross_sample_norm TMM --name_sample_by_basedir ./N116-rep1/abundance.tsv ./N116-rep2/abundance.tsv ./N116-rep3/abundance.tsv ./N116-rep4/abundance.tsv ./N116-rep5/abundance.tsv ./PSO1-rep1/abundance.tsv ./PSO1-rep2/abundance.tsv ./PSO1-rep3/abundance.tsv ./PSO1-rep4/abundance.tsv ./PSO1-rep5/abundance.tsv ./avr-rep1/abundance.tsv ./avr-rep2/abundance.tsv ./avr-rep3/abundance.tsv ./avr-rep4/abundance.tsv ./avr-rep5/abundance.tsv ./vir-rep1/abundance.tsv ./vir-rep2/abundance.tsv ./vir-rep3/abundance.tsv ./vir-rep4/abundance.tsv ./vir-rep5/abundance.tsv --out_prefix Published_genes_N116_PS01_VIRS_AVR
 
 
cd /home/pt40963/scratch/pea_aphid_RNAseq_20171104
wait
# --prep_reference (removed) already done
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep2_R1.fastq.gz --right N116-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep3_R1.fastq.gz --right N116-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep4_R1.fastq.gz --right N116-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left N116-rep5_R1.fastq.gz --right N116-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left PSO1-rep1_R1.fastq.gz --right PSO1-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left PSO1-rep2_R1.fastq.gz --right PSO1-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left PSO1-rep3_R1.fastq.gz --right PSO1-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left PSO1-rep4_R1.fastq.gz --right PSO1-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left PSO1-rep5_R1.fastq.gz --right PSO1-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left avr-rep1_R1.fastq.gz --right avr-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left avr-rep2_R1.fastq.gz --right avr-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left avr-rep3_R1.fastq.gz --right avr-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left avr-rep4_R1.fastq.gz --right avr-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left avr-rep5_R1.fastq.gz --right avr-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left vir-rep1_R1.fastq.gz --right vir-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left vir-rep2_R1.fastq.gz --right vir-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left vir-rep3_R1.fastq.gz --right vir-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left vir-rep4_R1.fastq.gz --right vir-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/Pea_aphid/final_genes/A.pisum_nt.fasta --seqType fq --left vir-rep5_R1.fastq.gz --right vir-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep5

 
 /home/pt40963/Downloads/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --cross_sample_norm TMM --name_sample_by_basedir ./N116-rep1/abundance.tsv ./N116-rep2/abundance.tsv ./N116-rep3/abundance.tsv ./N116-rep4/abundance.tsv ./N116-rep5/abundance.tsv ./PSO1-rep1/abundance.tsv ./PSO1-rep2/abundance.tsv ./PSO1-rep3/abundance.tsv ./PSO1-rep4/abundance.tsv ./PSO1-rep5/abundance.tsv ./avr-rep1/abundance.tsv ./avr-rep2/abundance.tsv ./avr-rep3/abundance.tsv ./avr-rep4/abundance.tsv ./avr-rep5/abundance.tsv ./vir-rep1/abundance.tsv ./vir-rep2/abundance.tsv ./vir-rep3/abundance.tsv ./vir-rep4/abundance.tsv ./vir-rep5/abundance.tsv --out_prefix Pea_PT_genes_N116_PS01_VIRS_AVR_RNAseq_denovo

 
 wait
 # --prep_reference (removed) already done
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --prep_reference --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta  --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left N116-rep2_R1.fastq.gz --right N116-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left N116-rep3_R1.fastq.gz --right N116-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left N116-rep4_R1.fastq.gz --right N116-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left N116-rep5_R1.fastq.gz --right N116-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left PSO1-rep1_R1.fastq.gz --right PSO1-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left PSO1-rep2_R1.fastq.gz --right PSO1-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left PSO1-rep3_R1.fastq.gz --right PSO1-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left PSO1-rep4_R1.fastq.gz --right PSO1-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left PSO1-rep5_R1.fastq.gz --right PSO1-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left avr-rep1_R1.fastq.gz --right avr-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left avr-rep2_R1.fastq.gz --right avr-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left avr-rep3_R1.fastq.gz --right avr-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left avr-rep4_R1.fastq.gz --right avr-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left avr-rep5_R1.fastq.gz --right avr-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left vir-rep1_R1.fastq.gz --right vir-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left vir-rep2_R1.fastq.gz --right vir-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left vir-rep3_R1.fastq.gz --right vir-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left vir-rep4_R1.fastq.gz --right vir-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/N116/Pea_N116_denovo.Trinity.fasta --seqType fq --left vir-rep5_R1.fastq.gz --right vir-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep5

 
 /home/pt40963/Downloads/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --cross_sample_norm TMM --name_sample_by_basedir ./N116-rep1/abundance.tsv ./N116-rep2/abundance.tsv ./N116-rep3/abundance.tsv ./N116-rep4/abundance.tsv ./N116-rep5/abundance.tsv ./PSO1-rep1/abundance.tsv ./PSO1-rep2/abundance.tsv ./PSO1-rep3/abundance.tsv ./PSO1-rep4/abundance.tsv ./PSO1-rep5/abundance.tsv ./avr-rep1/abundance.tsv ./avr-rep2/abundance.tsv ./avr-rep3/abundance.tsv ./avr-rep4/abundance.tsv ./avr-rep5/abundance.tsv ./vir-rep1/abundance.tsv ./vir-rep2/abundance.tsv ./vir-rep3/abundance.tsv ./vir-rep4/abundance.tsv ./vir-rep5/abundance.tsv --out_prefix Pea_N116_clone_specific_RNAseq_denovo

 wait
 # --prep_reference (removed) already done
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --prep_reference --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta  --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left N116-rep1_R1.fastq.gz --right N116-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left N116-rep2_R1.fastq.gz --right N116-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left N116-rep3_R1.fastq.gz --right N116-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left N116-rep4_R1.fastq.gz --right N116-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left N116-rep5_R1.fastq.gz --right N116-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir N116-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left PSO1-rep1_R1.fastq.gz --right PSO1-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left PSO1-rep2_R1.fastq.gz --right PSO1-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left PSO1-rep3_R1.fastq.gz --right PSO1-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left PSO1-rep4_R1.fastq.gz --right PSO1-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left PSO1-rep5_R1.fastq.gz --right PSO1-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir PSO1-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left avr-rep1_R1.fastq.gz --right avr-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left avr-rep2_R1.fastq.gz --right avr-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left avr-rep3_R1.fastq.gz --right avr-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left avr-rep4_R1.fastq.gz --right avr-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left avr-rep5_R1.fastq.gz --right avr-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir avr-rep5
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left vir-rep1_R1.fastq.gz --right vir-rep1_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep1
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left vir-rep2_R1.fastq.gz --right vir-rep2_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep2
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left vir-rep3_R1.fastq.gz --right vir-rep3_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep3
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left vir-rep4_R1.fastq.gz --right vir-rep4_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep4
/home/pt40963/Downloads/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl --transcripts /home/pt40963/scratch/Pea_aphid/clone_specific/PS01/Pea_PS01_denovo.Trinity.fasta --seqType fq --left vir-rep5_R1.fastq.gz --right vir-rep5_R2.fastq.gz --est_method kallisto --SS_lib_type FR --thread_count 16 --trinity_mode --output_dir vir-rep5

 
 /home/pt40963/Downloads/trinityrnaseq-2.1.1/util/abundance_estimates_to_matrix.pl --est_method kallisto --cross_sample_norm TMM --name_sample_by_basedir ./N116-rep1/abundance.tsv ./N116-rep2/abundance.tsv ./N116-rep3/abundance.tsv ./N116-rep4/abundance.tsv ./N116-rep5/abundance.tsv ./PSO1-rep1/abundance.tsv ./PSO1-rep2/abundance.tsv ./PSO1-rep3/abundance.tsv ./PSO1-rep4/abundance.tsv ./PSO1-rep5/abundance.tsv ./avr-rep1/abundance.tsv ./avr-rep2/abundance.tsv ./avr-rep3/abundance.tsv ./avr-rep4/abundance.tsv ./avr-rep5/abundance.tsv ./vir-rep1/abundance.tsv ./vir-rep2/abundance.tsv ./vir-rep3/abundance.tsv ./vir-rep4/abundance.tsv ./vir-rep5/abundance.tsv --out_prefix Pea_PS01_clone_specific_RNAseq_denovo
