cd  /storage/home/users/pjt6/pea_aphid/head_RNAseq

#rm -rf star_indicies
#mkdir star_indicies

#/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR  --runMode genomeGenerate --runThreadN 16 --genomeDir ./star_indicies --genomeFastaFiles ../Pea_aphid_genome_no_discriptions.fasta

/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_A17_1_R1_paired.fq.gz N116_A17_1_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_A17_1
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_A17_3_R1_paired.fq.gz N116_A17_3_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_A17_3
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_A17_2_R1_paired.fq.gz N116_A17_2_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_A17_2



/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_1_R1_paired.fq.gz N116_D2A_1_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_1
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_2_R1_paired.fq.gz N116_D2A_2_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_2
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_3_R1_paired.fq.gz N116_D2A_3_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_2_R1_paired.fq.gz N116_D2A_2_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_2
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_1_R1_paired.fq.gz N116_D2A_1_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_1
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  N116_D2A_3_R1_paired.fq.gz N116_D2A_3_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_N116_DZA_3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_D2A_1_R1_paired.fq.gz PS01_D2A_1_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_DZA_1
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_D2A_2_R1_paired.fq.gz PS01_D2A_2_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_DZA_2
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_D2A_3_R1_paired.fq.gz PS01_D2A_3_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_DZA_3


/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_A17_2_R1_paired.fq.gz PS01_A17_2_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_A17_2
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_A17_1_R1_paired.fq.gz PS01_A17_1_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_A17_1
/shelf/apps/pjt6/apps/STAR-master/bin/Linux_x86_64_static/STAR --genomeDir star_indicies/ --limitGenomeGenerateRAM 285554136874 --limitBAMsortRAM 90554136874 --runThreadN 16   --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFilterMismatchNmax 10  --outFilterMultimapNmax 3 --readFilesIn  PS01_A17_3_R1_paired.fq.gz PS01_A17_3_R2_paired.fq.gz  --outFileNamePrefix  pea_aphid_PS01_A17_3

echo ................. all mapping is done .......................................

